# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb07f0ff93c766102e4f2457a26d8b208d921fe7e95dbbba8effb6d4a8a1632613574ab7d7ec5b720f9128cc0f67ba3e31311efc11b2bd214fd92a2f400625b2

test:
  secret_key_base: 96476b785af0e781175675c6b61bb32f2217d456030c1f4c31cb172ee5454621b70c85a76ebf05110c0314db5173385fadc5e82c14b38fc6ae9c7c9e9646740d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
